#!/bin/bash -eu

function apt_get() {
    sudo DEBIAN_FRONTEND=noninteractive apt-get \
        -y -o Dpkg::Options::='--force-confold' $*
}

apt_get install --no-install-recommends \
    build-essential \
    libmysqlclient-dev \
    libpq-dev \
    mysql-server \
    pgbouncer \
    postgresql \
    python3-dev \
    python3-fixtures \
    python3-mysqldb \
    python3-pgbouncer \
    python3-psycopg2 \
    python3-setuptools \
    python3-testresources \
    python3-timeline \
    python3-transaction \
    python3-twisted \
    python3-zope.component \
    python3-zope.security \
    tox


echo " * All Done!"
